# Netlify dev
# https://cli.netlify.com/netlify-dev/#netlifytoml-dev-block

[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"
[dev]
  framework = "#custom"
  command = "npm run dev:webpack"
  targetPort = 8079
  port = 8080
  publish = "dist"
  autoLaunch = false